server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: power-duel-backend

  datasource:
    url: jdbc:h2:file:./data/power-duel;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: https://{your-site}/login/oauth2/code/googlec

# Where to send the browser after a successful Google login.
app:
  frontend-success-redirect: (your-redirect-link)
